backend:
  name: git-gateway
  branch: main

# Enable local development mode (disable for production)
# local_backend: true

# Media storage configuration
media_folder: "public/images"
public_folder: "/images"

# Collections configuration
collections:
  # Books collection
  - name: "books"
    label: "Books"
    folder: "src/content/books"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string", default: "Dane Griggs" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Cover Image", name: "cover", widget: "image" }
      - { label: "Series", name: "series", widget: "string", required: false }
      - { label: "Series Order", name: "seriesOrder", widget: "number", required: false }
      - { label: "Publication Date", name: "pubDate", widget: "datetime" }
      - { label: "Rating", name: "rating", widget: "number", value_type: "float", min: 0, max: 5, step: 0.1, default: 0 }
      - { label: "Rating Count", name: "ratingCount", widget: "number", default: 0 }
      - label: "Species"
        name: "species"
        widget: "relation"
        collection: "species"
        search_fields: ["name"]
        value_field: "slug"
        display_fields: ["name"]
        multiple: true
        default: []
      - label: "Heat Level"
        name: "heatLevel"
        widget: "select"
        options: ["mild", "medium", "spicy"]
        default: "medium"
      - label: "Setting"
        name: "setting"
        widget: "relation"
        collection: "locations"
        search_fields: ["name"]
        value_field: "slug"
        display_fields: ["name"]
        multiple: true
        default: []
      - { label: "Genres", name: "genres", widget: "list", default: [] }
      - { label: "Available on Kindle Unlimited", name: "isKU", widget: "boolean", default: true }
      - { label: "Amazon URL", name: "amazonUrl", widget: "string", required: false }
      - { label: "Goodreads URL", name: "goodreadsUrl", widget: "string", required: false }
      - { label: "Price", name: "price", widget: "string", required: false }
      - { label: "Word Count", name: "wordCount", widget: "number", required: false }
      - { label: "Page Count", name: "pageCount", widget: "number", required: false }
      - label: "Status"
        name: "status"
        widget: "select"
        options: ["published", "pre-order", "upcoming", "draft"]
        default: "published"
      - { label: "Featured Book", name: "featured", widget: "boolean", default: false }
      - { label: "Content", name: "body", widget: "markdown" }

  # Series collection
  - name: "series"
    label: "Series"
    folder: "src/content/series"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Cover Image", name: "cover", widget: "image", required: false }
      - { label: "Book Count", name: "bookCount", widget: "number" }
      - label: "Completion Status"
        name: "completionStatus"
        widget: "select"
        options: ["ongoing", "complete"]
        default: "ongoing"
      - { label: "Start Date", name: "startDate", widget: "datetime" }
      - { label: "Completion Date", name: "completionDate", widget: "datetime", required: false }
      - label: "Species"
        name: "species"
        widget: "relation"
        collection: "species"
        search_fields: ["name"]
        value_field: "slug"
        display_fields: ["name"]
        multiple: true
        default: []
      - { label: "Overall Rating", name: "overallRating", widget: "number", value_type: "float", min: 0, max: 5, step: 0.1, default: 0 }
      - { label: "Total Ratings", name: "totalRatings", widget: "number", default: 0 }
      - { label: "World Building Notes", name: "worldBuilding", widget: "text", required: false }
      - { label: "Reading Order", name: "readingOrder", widget: "list", default: [] }
      - { label: "Featured Series", name: "featured", widget: "boolean", default: false }
      - { label: "Content", name: "body", widget: "markdown" }

  # Blog collection
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Publication Date", name: "pubDate", widget: "datetime" }
      - { label: "Updated Date", name: "updatedDate", widget: "datetime", required: false }
      - { label: "Hero Image", name: "heroImage", widget: "image", required: false }
      - { label: "Tags", name: "tags", widget: "list", default: [] }
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["alien-cultures", "world-building", "writing-process", "behind-scenes"]
        default: "writing-process"
      - { label: "Content", name: "body", widget: "markdown" }

  # Testimonials collection
  - name: "testimonials"
    label: "Testimonials"
    folder: "src/content/testimonials"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Reviewer Name", name: "reviewerName", widget: "string" }
      - label: "Platform"
        name: "reviewerPlatform"
        widget: "select"
        options: ["amazon", "goodreads", "bookbub", "facebook", "email"]
        default: "amazon"
      - { label: "Rating", name: "rating", widget: "number", min: 1, max: 5 }
      - { label: "Quote", name: "quote", widget: "text" }
      - { label: "Book Title", name: "bookTitle", widget: "string", required: false }
      - { label: "Verified Purchase", name: "verified", widget: "boolean", default: false }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Featured Testimonial", name: "featured", widget: "boolean", default: false }
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["character-development", "world-building", "romance", "humor", "overall"]
        default: "overall"
      - { label: "Content", name: "body", widget: "markdown", required: false }

  # Characters collection
  - name: "characters"
    label: "Characters"
    folder: "src/content/characters"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - label: "Books"
        name: "books"
        widget: "relation"
        collection: "books"
        search_fields: ["title"]
        value_field: "{{slug}}"
        display_fields: ["title"]
        multiple: true
        default: []
        options_length: 200
      - label: "Cameos"
        name: "cameos"
        widget: "relation"
        collection: "books"
        search_fields: ["title"]
        value_field: "{{slug}}"
        display_fields: ["title"]
        multiple: true
        default: []
        required: false
        options_length: 200
      - { label: "Image", name: "image", widget: "image", required: false }
      - label: "Species"
        name: "species"
        widget: "relation"
        collection: "species"
        search_fields: ["name"]
        value_field: "slug"
        display_fields: ["name"]
        required: false
      - { label: "Content", name: "body", widget: "markdown", required: false }

  # Site settings
  - name: "settings"
    label: "Site Settings"
    folder: "src/content/settings"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Site Title", name: "siteTitle", widget: "string", required: false }
      - { label: "Site Description", name: "siteDescription", widget: "text", required: false }
      - { label: "Author Name", name: "authorName", widget: "string", required: false }
      - { label: "Author Bio", name: "authorBio", widget: "text", required: false }
      - { label: "Tagline", name: "tagline", widget: "string", required: false }
      - label: "Social Links"
        name: "socialLinks"
        widget: "object"
        required: false
        fields:
          - { label: "Facebook", name: "facebook", widget: "string", required: false }
          - { label: "Goodreads", name: "goodreads", widget: "string", required: false }
          - { label: "Twitter", name: "twitter", widget: "string", required: false }
          - { label: "Instagram", name: "instagram", widget: "string", required: false }
          - { label: "Email", name: "email", widget: "string", required: false }
      - label: "Statistics"
        name: "stats"
        widget: "object"
        required: false
        fields:
          - { label: "Books Published", name: "booksPublished", widget: "number", required: false }
          - { label: "Pages Read", name: "pagesRead", widget: "string", required: false }
          - { label: "Reader Ratings", name: "readerRatings", widget: "string", required: false }
          - { label: "Series", name: "seriesComplete", widget: "number", required: false }
      - label: "Newsletter"
        name: "newsletter"
        widget: "object"
        required: false
        fields:
          - { label: "Lead Magnet Title", name: "leadMagnetTitle", widget: "string", required: false }
          - { label: "Lead Magnet Description", name: "leadMagnetDescription", widget: "text", required: false }
          - { label: "Benefits", name: "benefits", widget: "list", required: false }
      - { label: "Content", name: "body", widget: "markdown", required: false }

  # Species collection
  - name: "species"
    label: "Species"
    folder: "src/content/species"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - label: "Series"
        name: "series"
        widget: "relation"
        collection: "series"
        search_fields: ["title"]
        value_field: "{{slug}}"
        display_fields: ["title"]
        multiple: true
        default: []
        required: false
        options_length: 200
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Physical Traits", name: "physicalTraits", widget: "text", required: false }
      - { label: "Culture Notes", name: "cultureNotes", widget: "text", required: false }
      - { label: "Biology Notes", name: "biologyNotes", widget: "text", required: false }
      - { label: "Content", name: "body", widget: "markdown", required: false }

  # Locations collection
  - name: "locations"
    label: "Locations"
    folder: "src/content/locations"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Environment Type", name: "environmentType", widget: "string", required: false }
      - { label: "Content", name: "body", widget: "markdown", required: false }

  # Pages collection
  - name: "pages"
    label: "Pages"
    folder: "src/content/pages"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Page Type", name: "pageType", widget: "string" }
      - label: "Hero Section"
        name: "hero"
        widget: "object"
        fields:
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Tagline", name: "tagline", widget: "string", required: false }
      - label: "Author Bio"
        name: "authorBio"
        widget: "object"
        fields:
          - { label: "Main Bio", name: "mainBio", widget: "text", required: false }
          - { label: "Secondary Bio", name: "secondaryBio", widget: "text", required: false }
          - { label: "Tertiary Bio", name: "tertiaryBio", widget: "text", required: false }
      - label: "Philosophy Cards"
        name: "philosophyCards"
        widget: "list"
        required: false
        fields:
          - label: "Icon"
            name: "icon"
            widget: "select"
            required: false
            options:
              - { label: "🔬 Microscope", value: "🔬" }
              - { label: "🧬 DNA", value: "🧬" }
              - { label: "🌌 Galaxy", value: "🌌" }
              - { label: "⚗️ Alembic", value: "⚗️" }
              - { label: "🧪 Test Tube", value: "🧪" }
              - { label: "🔭 Telescope", value: "🔭" }
              - { label: "⚛️ Atom", value: "⚛️" }
              - { label: "🌠 Shooting Star", value: "🌠" }
              - { label: "💝 Gift Heart", value: "💝" }
              - { label: "❤️ Red Heart", value: "❤️" }
              - { label: "💕 Two Hearts", value: "💕" }
              - { label: "💖 Sparkling Heart", value: "💖" }
              - { label: "🥰 Smiling Face with Hearts", value: "🥰" }
              - { label: "😍 Heart Eyes", value: "😍" }
              - { label: "💘 Heart with Arrow", value: "💘" }
              - { label: "💗 Growing Heart", value: "💗" }
              - { label: "🧠 Brain", value: "🧠" }
              - { label: "💡 Light Bulb", value: "💡" }
              - { label: "🎯 Target", value: "🎯" }
              - { label: "📚 Books", value: "📚" }
              - { label: "🤓 Nerd Face", value: "🤓" }
              - { label: "✨ Sparkles", value: "✨" }
              - { label: "💭 Thought Bubble", value: "💭" }
              - { label: "🎲 Die", value: "🎲" }
              - { label: "✍️ Writing Hand", value: "✍️" }
              - { label: "📖 Open Book", value: "📖" }
              - { label: "📝 Memo", value: "📝" }
              - { label: "📜 Scroll", value: "📜" }
              - { label: "✒️ Pen", value: "✒️" }
              - { label: "🖋️ Fountain Pen", value: "🖋️" }
              - { label: "📑 Bookmark Tabs", value: "📑" }
              - { label: "🌹 Rose", value: "🌹" }
              - { label: "💫 Dizzy", value: "💫" }
              - { label: "💍 Ring", value: "💍" }
              - { label: "👫 Couple", value: "👫" }
              - { label: "💏 Kiss", value: "💏" }
              - { label: "🌺 Hibiscus", value: "🌺" }
              - { label: "🚀 Rocket", value: "🚀" }
              - { label: "🛸 UFO", value: "🛸" }
              - { label: "🌟 Star", value: "🌟" }
              - { label: "⭐ White Star", value: "⭐" }
              - { label: "🌙 Moon", value: "🌙" }
              - { label: "💻 Laptop", value: "💻" }
              - { label: "🤖 Robot", value: "🤖" }
              - { label: "🛰️ Satellite", value: "🛰️" }
              - { label: "🤝 Handshake", value: "🤝" }
              - { label: "👥 People", value: "👥" }
              - { label: "💑 Couple with Heart", value: "💑" }
              - { label: "🫶 Heart Hands", value: "🫶" }
              - { label: "🙌 Raising Hands", value: "🙌" }
              - { label: "🎭 Theater Masks", value: "🎭" }
              - { label: "🎪 Circus Tent", value: "🎪" }
              - { label: "🌈 Rainbow", value: "🌈" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
      - label: "Connect Section"
        name: "connectSection"
        widget: "object"
        required: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Content", name: "body", widget: "markdown", required: false }

# Site configuration
site_url: https://danegriggs.com
display_url: https://danegriggs.com
logo_url: https://danegriggs.com/images/logo.png

# Editor configuration
editor:
  preview: true

# Publishing configuration - use simple mode for direct publishing
# publish_mode: editorial_workflow